"""Every series we use: where it came from, what it spans, and whether it reaches.

Written because the question "is our data good enough?" only has an answer
relative to what the paper needs, and what the paper needs is not the 1970 it
states. Section 3.4.3 requires a 3000-day training window and then an 8-year
validation window before the first out-of-sample day, so a series starting at
1970-01-01 puts the first tradeable day near 1990 -- which is the point. A
series that starts late does not shorten the sample at one end; it deletes the
front of the reported 1990-2023 period.

Prints one row per series with its true observed span, the sha256 that the
frozen config pins, and how much slack it has against the paper's requirement.
Writes the same to artifacts/data-provenance/ so it can be attached to an email
without being regenerated by hand.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import pandas as pd  # noqa: E402

from adaptive_jump.config import load_config  # noqa: E402

OUT = ROOT / "artifacts" / "data-provenance"
CONFIG = ROOT / "research-expanding-v9-1.toml"

# The paper's stated span, and what the procedure actually needs before it.
PAPER_START = pd.Timestamp("1970-01-01")
PAPER_END = pd.Timestamp("2023-12-31")
FIT_WINDOW_DAYS = 3000          # trading days, Section 3.4.2
VALIDATION_YEARS = 8            # Section 3.4.3
OOS_START = pd.Timestamp("1990-01-02")

# Where each pinned input was fetched from. Recorded here because a canonical
# series is built from these and a URL in a builder docstring is not provenance.
INPUT_SOURCES = {
    "sp500_price_daily.csv": (
        "Yahoo Finance chart API, ^GSPC",
        "https://query1.finance.yahoo.com/v8/finance/chart/%5EGSPC?interval=1d"),
    "sp500_tr_daily.csv": (
        "Yahoo Finance chart API, ^SP500TR (official S&P 500 Total Return)",
        "https://query1.finance.yahoo.com/v8/finance/chart/%5ESP500TR?interval=1d"),
    "shiller_sp500_monthly.csv": (
        "Robert Shiller monthly S&P 500 price and dividend series",
        "https://raw.githubusercontent.com/datasets/s-and-p-500/main/data/data.csv"),
    "ff_us_daily.csv": (
        "Kenneth French daily US research factors (CRSP universe)",
        "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html"),
    "stooq_dax_daily.csv": (
        "Stooq ^dax daily close, DAX performance index",
        "https://stooq.com/q/d/?s=%5Edax"),
    "n225_price_daily.csv": (
        "Nikkei 225 price index daily close",
        "https://finance.yahoo.com/quote/%5EN225/history/"),
    "n225tr_official_merged.csv": (
        "Nikkei 225 Total Return, official Nikkei Inc. values via Investing.com",
        "https://indexes.nikkei.co.jp/en/nkave/index/profile?idx=nk225tr"),
    "jst_japan_eq.csv": (
        "Jorda-Schularick-Taylor Macrohistory Database, Japan equity dividend yield",
        "https://www.macrohistory.net/database/"),
    "jp_equity_tr_full.csv": (
        "Nikkei 225 Total Return, mirror export used for the 2011+ segment",
        "https://indexes.nikkei.co.jp/en/nkave/index/profile?idx=nk225tr"),
    "INTGSTDEM193N.csv": (
        "FRED / IMF IFS, Germany 3-month Treasury bill rate",
        "https://fred.stlouisfed.org/series/INTGSTDEM193N"),
    "INTGSTJPM193N.csv": (
        "FRED / IMF IFS, Japan 3-month Treasury bill rate",
        "https://fred.stlouisfed.org/series/INTGSTJPM193N"),
    "IR3TIB01DEM156N.csv": (
        "FRED / OECD MEI, Germany 3-month interbank rate",
        "https://fred.stlouisfed.org/series/IR3TIB01DEM156N"),
    "ecb_3m_aaa.csv": (
        "ECB Data Portal, euro-area AAA government 3-month spot yield",
        "https://data.ecb.europa.eu/data/datasets/YC"),
    "boj_straclu3m.csv": (
        "Bank of Japan, 3-month uncollateralised overnight call rate",
        "https://www.stat-search.boj.or.jp/"),
}


def span(path: Path) -> tuple:
    """First date, last date, row count and hash, for any of our input shapes.

    The raw files disagree about almost everything: French's factors carry three
    lines of preamble and 8-digit integer dates, the ECB export is 40 columns
    wide, and the FRED downloads name their date column three different ways.
    Rather than special-case each, read leniently and pick whichever column
    parses as dates for most of its rows.
    """
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    frame = None
    for skiprows in (0, 1, 2, 3, 4):
        try:
            # low_memory belongs to the C parser only; passing it here raises.
            candidate = pd.read_csv(path, skiprows=skiprows, engine="python",
                                    on_bad_lines="skip")
        except (pd.errors.ParserError, ValueError):
            continue
        if len(candidate.columns) >= 2 and len(candidate):
            frame = candidate
            break
    if frame is None:
        return pd.NaT, pd.NaT, 0, digest

    best, best_dates = None, None
    for column in frame.columns:
        raw = frame[column].astype(str).str.strip()
        # French stamps dates as 19260701; everything else is ISO-like.
        parsed = (pd.to_datetime(raw, format="%Y%m%d", errors="coerce")
                  if raw.str.fullmatch(r"\d{8}").mean() > 0.5
                  else pd.to_datetime(raw, errors="coerce", format="mixed"))
        share = parsed.notna().mean()
        if share > 0.5 and (best is None or share > best):
            best, best_dates = share, parsed.dropna()
    if best_dates is None or best_dates.empty:
        return pd.NaT, pd.NaT, len(frame), digest
    return best_dates.min(), best_dates.max(), len(frame), digest


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    config = load_config(CONFIG)

    rows = []
    for market in config.markets:
        for kind, source in (("equity", market.equity), ("cash", market.cash)):
            path_text = source.settings.get("file_path")
            observed = source.settings.get("source_start_observed")
            if path_text:
                path = ROOT / path_text
                first, last, count, digest = span(path)
                pinned = source.settings.get("sha256", "")
                ok = digest == pinned
            else:
                first = pd.Timestamp(observed) if observed else pd.NaT
                last, count, ok = pd.NaT, None, None
                path_text = f"(fetched live: {source.settings.get('retrieval_url', '')})"
            rows.append({
                "market": market.id, "leg": kind, "source_id": source.source_id,
                "provider": source.provider,
                "canonical_url": source.settings.get("canonical_url", ""),
                "file": path_text,
                "first": first, "last": last, "rows": count,
                "declared_start": observed,
                "sha256_matches_config": ok,
            })
    canonical = pd.DataFrame(rows)
    canonical.to_csv(OUT / "canonical-series.csv", index=False,
                     lineterminator="\n")

    inputs = []
    for name, (description, url) in sorted(INPUT_SOURCES.items()):
        path = ROOT / "data" / "external" / "inputs" / name
        if not path.is_file():
            inputs.append({"file": name, "description": description, "url": url,
                           "first": pd.NaT, "last": pd.NaT, "rows": 0,
                           "sha256": "MISSING"})
            continue
        first, last, count, digest = span(path)
        inputs.append({"file": name, "description": description, "url": url,
                       "first": first, "last": last, "rows": count,
                       "sha256": digest})
    input_frame = pd.DataFrame(inputs)
    input_frame.to_csv(OUT / "raw-inputs.csv", index=False, lineterminator="\n")

    lines = ["NGUỒN DỮ LIỆU — chuỗi chuẩn hoá dùng trong hợp đồng "
             f"{config.config_id}", ""]
    for r in canonical.itertuples():
        head = f"  {r.market} {r.leg:<7} {r.source_id}"
        lines.append(head)
        lines.append(f"      nguồn : {r.canonical_url}")
        lines.append(f"      file  : {r.file}")
        if pd.notna(r.last):
            lines.append(f"      phủ   : {r.first.date()} .. {r.last.date()}"
                         f"  ({r.rows} dòng)"
                         f"   hash khớp config: "
                         f"{'có' if r.sha256_matches_config else 'KHÔNG'}")
        else:
            lines.append(f"      phủ   : từ {r.declared_start} (tải trực tiếp)")
        lines.append("")

    lines.append("ĐỦ SỚM CHƯA? Paper nói dữ liệu bắt đầu 1970, nhưng quy trình")
    lines.append("cần 3000 phiên huấn luyện + 8 năm kiểm định TRƯỚC ngày ngoài")
    lines.append("mẫu đầu tiên, nên chuỗi phải bắt đầu sớm hơn 1990 khoảng 20")
    lines.append("năm. Thiếu ở đầu chuỗi thì không mất phần đầu dữ liệu — mà")
    lines.append("mất phần đầu của chính giai đoạn báo cáo 1990-2023.")
    lines.append("")
    lines.append(f"  {'chuỗi':<22}{'bắt đầu':>12}{'so với 1970':>14}"
                 f"{'so với mốc cần':>17}")
    need = OOS_START - pd.DateOffset(years=VALIDATION_YEARS) \
        - pd.DateOffset(days=int(FIT_WINDOW_DAYS * 365.25 / 252))
    for r in canonical.itertuples():
        if pd.isna(r.first):
            continue
        d70 = (PAPER_START - r.first).days / 365.25
        dneed = (need - r.first).days / 365.25
        lines.append(f"  {r.market + ' ' + r.leg:<22}{str(r.first.date()):>12}"
                     f"{d70:>+13.1f}n{dneed:>+16.1f}n")
    lines.append(f"\n  mốc cần thiết ~ {need.date()} "
                 f"(= {OOS_START.date()} lùi 8 năm kiểm định "
                 f"và {FIT_WINDOW_DAYS} phiên huấn luyện)")
    lines.append("  số dương = chuỗi bắt đầu SỚM hơn mốc, tức là đủ.")

    lines.append("\n\nDỮ LIỆU THÔ ĐƯỢC GHIM HASH (nguyên liệu để dựng các chuỗi trên)")
    lines.append("")
    for r in input_frame.itertuples():
        lines.append(f"  {r.file}")
        lines.append(f"      {r.description}")
        lines.append(f"      {r.url}")
        if pd.notna(r.first):
            lines.append(f"      {r.first.date()} .. {r.last.date()}"
                         f"  ({r.rows} dòng)  sha256 {r.sha256[:16]}…")
        lines.append("")

    report = "\n".join(lines) + "\n"
    (OUT / "report.txt").write_text(report, encoding="utf-8")
    print(report)
    print(f"đã ghi {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
